source 'https://rubygems.org'

ruby '2.2.0'

gem 'sinatra', :require => 'sinatra/base'
gem 'json'
gem 'thin'
gem 'foreman'
gem 'redis-sinatra'
gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"
gem 'delayed_job_active_record'
gem 'sidekiq', :git => 'https://github.com/mperham/sidekiq'

group :development do
  gem "rspec"
end
